name: ‚ôªÔ∏è Sync Labels

on:
  workflow_dispatch:

jobs:
  labels:
    name: ‚ôªÔ∏è Sync labels
    runs-on: ubuntu-20.04
    permissions:
      issues: write
      contents: read 
    steps:
      - name: ‚§µÔ∏è Check out code from GitHub
        uses: actions/checkout@v6

      - name: üöÄ Run Label Sync
        uses: srealmoreno/label-sync-action@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GH_TOKEN }}
